version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - 'database:/var/lib/postgresql/data'
    ports:
      - "32770:5432"
    environment:
      POSTGRES_DATABASE: twoscoops
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: tom
volumes:
  database:
